void glue_fdc_ioport_read(uint8_t reg, uint8_t value);
void glue_fdc_ioport_write(uint8_t reg, uint8_t value);
void glue_fdctrl_tc_pulse(int level);
void glue_pflash_chip_erase_invalid(const char *name, uint64_t offset);
void glue_pflash_chip_erase_start(const char *name);
void glue_pflash_data_read(const char *name, uint64_t offset, unsigned size, uint32_t value);
void glue_pflash_data_write(const char *name, uint64_t offset, unsigned size, uint32_t value, uint64_t counter);
void glue_pflash_device_id(const char *name, uint16_t id);
void glue_pflash_device_info(const char *name, uint64_t offset);
void glue_pflash_erase_complete(const char *name);
void glue_pflash_erase_timeout(const char *name, int count);
void glue_pflash_io_read(const char *name, uint64_t offset, unsigned int size, uint32_t value, uint8_t cmd, uint8_t wcycle);
void glue_pflash_io_write(const char *name, uint64_t offset, unsigned int size, uint32_t value, uint8_t wcycle);
void glue_pflash_manufacturer_id(const char *name, uint16_t id);
void glue_pflash_mode_read_array(const char *name);
void glue_pflash_postload_cb(const char *name);
void glue_pflash_read_done(const char *name, uint64_t offset, uint64_t ret);
void glue_pflash_read_status(const char *name, uint32_t ret);
void glue_pflash_read_unknown_state(const char *name, uint8_t cmd);
void glue_pflash_reset(const char *name);
void glue_pflash_sector_erase_start(const char *name, int width1, uint64_t start, int width2, uint64_t end);
void glue_pflash_timer_expired(const char *name, uint8_t cmd);
void glue_pflash_unlock0_failed(const char *name, uint64_t offset, uint8_t cmd, uint16_t addr0);
void glue_pflash_unlock1_failed(const char *name, uint64_t offset, uint8_t cmd);
void glue_pflash_unsupported_device_configuration(const char *name, uint8_t width, uint8_t max);
void glue_pflash_write(const char *name, const char *str);
void glue_pflash_write_block(const char *name, uint32_t value);
void glue_pflash_write_block_erase(const char *name, uint64_t offset, uint64_t len);
void glue_pflash_write_failed(const char *name, uint64_t offset, uint8_t cmd);
void glue_pflash_write_invalid(const char *name, uint8_t cmd);
void glue_pflash_write_invalid_command(const char *name, uint8_t cmd);
void glue_pflash_write_invalid_state(const char *name, uint8_t cmd, int wc);
void glue_pflash_write_start(const char *name, uint8_t cmd);
void glue_pflash_write_unknown(const char *name, uint8_t cmd);
void glue_virtio_blk_req_complete(void *vdev, void *req, int status);
void glue_virtio_blk_rw_complete(void *vdev, void *req, int ret);
void glue_virtio_blk_handle_write(void *vdev, void *req, uint64_t sector, size_t nsectors);
void glue_virtio_blk_handle_read(void *vdev, void *req, uint64_t sector, size_t nsectors);
void glue_virtio_blk_submit_multireq(void *vdev, void *mrb, int start, int num_reqs, uint64_t offset, size_t size, bool is_write);
void glue_hd_geometry_lchs_guess(void *blk, int cyls, int heads, int secs);
void glue_hd_geometry_guess(void *blk, uint32_t cyls, uint32_t heads, uint32_t secs, int trans);
void glue_xen_block_realize(const char *type, uint32_t disk, uint32_t partition);
void glue_xen_block_connect(const char *type, uint32_t disk, uint32_t partition);
void glue_xen_block_disconnect(const char *type, uint32_t disk, uint32_t partition);
void glue_xen_block_unrealize(const char *type, uint32_t disk, uint32_t partition);
void glue_xen_block_size(const char *type, uint32_t disk, uint32_t partition, int64_t sectors);
void glue_xen_disk_realize(void);
void glue_xen_disk_unrealize(void);
void glue_xen_cdrom_realize(void);
void glue_xen_cdrom_unrealize(void);
void glue_xen_block_blockdev_add(char *str);
void glue_xen_block_blockdev_del(const char *node_name);
void glue_xen_block_device_create(unsigned int number);
void glue_xen_block_device_destroy(unsigned int number);
void glue_m25p80_flash_erase(void *s, int offset, uint32_t len);
void glue_m25p80_programming_zero_to_one(void *s, uint32_t addr, uint8_t prev, uint8_t data);
void glue_m25p80_reset_done(void *s);
void glue_m25p80_command_decoded(void *s, uint32_t cmd);
void glue_m25p80_complete_collecting(void *s, uint32_t cmd, int n, uint8_t ear, uint32_t cur_addr);
void glue_m25p80_populated_jedec(void *s);
void glue_m25p80_chip_erase(void *s);
void glue_m25p80_select(void *s, const char *what);
void glue_m25p80_page_program(void *s, uint32_t addr, uint8_t tx);
void glue_m25p80_transfer(void *s, uint8_t state, uint32_t len, uint8_t needed, uint32_t pos, uint32_t cur_addr, uint8_t t);
void glue_m25p80_read_byte(void *s, uint32_t addr, uint8_t v);
void glue_m25p80_read_data(void *s, uint32_t pos, uint8_t v);
void glue_m25p80_binding(void *s);
void glue_m25p80_binding_no_bdrv(void *s);
