void glue_adb_device_kbd_no_key(void);
void glue_adb_device_kbd_writereg(int reg, uint8_t val);
void glue_adb_device_kbd_readreg(int reg, uint8_t val0, uint8_t val1);
void glue_adb_device_kbd_request_change_addr(int devaddr);
void glue_adb_device_kbd_request_change_addr_and_handler(int devaddr, int handler);
void glue_adb_device_mouse_flush(void);
void glue_adb_device_mouse_writereg(int reg, uint8_t val);
void glue_adb_device_mouse_readreg(int reg, uint8_t val0, uint8_t val1);
void glue_adb_device_mouse_request_change_addr(int devaddr);
void glue_adb_device_mouse_request_change_addr_and_handler(int devaddr, int handler);
void glue_adb_bus_request(uint8_t addr, const char *cmd, int size);
void glue_adb_bus_request_done(uint8_t addr, const char *cmd, int size);
void glue_adb_bus_autopoll_block(bool blocked);
void glue_adb_bus_autopoll_cb(uint16_t mask);
void glue_adb_bus_autopoll_cb_done(uint16_t mask);
void glue_pckbd_kbd_read_data(uint32_t val);
void glue_pckbd_kbd_read_status(int status);
void glue_pckbd_outport_write(uint32_t val);
void glue_pckbd_kbd_write_command(uint64_t val);
void glue_pckbd_kbd_write_data(uint64_t val);
void glue_ps2_put_keycode(void *opaque, int keycode);
void glue_ps2_keyboard_event(void *opaque, int qcode, int down, unsigned int modifier, unsigned int modifiers, int set, int xlate);
void glue_ps2_read_data(void *opaque);
void glue_ps2_set_ledstate(void *s, int ledstate);
void glue_ps2_reset_keyboard(void *s);
void glue_ps2_write_keyboard(void *opaque, int val);
void glue_ps2_keyboard_set_translation(void *opaque, int mode);
void glue_ps2_mouse_send_packet(void *s, int dx1, int dy1, int dz1, int b);
void glue_ps2_mouse_fake_event(void *opaque);
void glue_ps2_write_mouse(void *opaque, int val);
void glue_ps2_kbd_reset(void *opaque);
void glue_ps2_mouse_reset(void *opaque);
void glue_ps2_kbd_init(void *s);
void glue_ps2_mouse_init(void *s);
void glue_hid_kbd_queue_full(void);
void glue_hid_kbd_queue_empty(void);
void glue_tsc2005_sense(const char *state);
void glue_virtio_input_queue_full(void);
void glue_lasips2_reg_read(unsigned int size, int id, uint64_t addr, const char *name, uint64_t val);
void glue_lasips2_reg_write(unsigned int size, int id, uint64_t addr, const char *name, uint64_t val);
void glue_lasips2_intr(unsigned int val);
