void glue_visit_free(void *v);
void glue_visit_complete(void *v, void *opaque);
void glue_visit_start_struct(void *v, const char *name, void *obj, size_t size);
void glue_visit_check_struct(void *v);
void glue_visit_end_struct(void *v, void *obj);
void glue_visit_start_list(void *v, const char *name, void *obj, size_t size);
void glue_visit_next_list(void *v, void *tail, size_t size);
void glue_visit_check_list(void *v);
void glue_visit_end_list(void *v, void *obj);
void glue_visit_start_alternate(void *v, const char *name, void *obj, size_t size);
void glue_visit_end_alternate(void *v, void *obj);
void glue_visit_optional(void *v, const char *name, bool *present);
void glue_visit_policy_reject(void *v, const char *name);
void glue_visit_policy_skip(void *v, const char *name);
void glue_visit_type_enum(void *v, const char *name, int *obj);
void glue_visit_type_int(void *v, const char *name, int64_t *obj);
void glue_visit_type_uint8(void *v, const char *name, uint8_t *obj);
void glue_visit_type_uint16(void *v, const char *name, uint16_t *obj);
void glue_visit_type_uint32(void *v, const char *name, uint32_t *obj);
void glue_visit_type_uint64(void *v, const char *name, uint64_t *obj);
void glue_visit_type_int8(void *v, const char *name, int8_t *obj);
void glue_visit_type_int16(void *v, const char *name, int16_t *obj);
void glue_visit_type_int32(void *v, const char *name, int32_t *obj);
void glue_visit_type_int64(void *v, const char *name, int64_t *obj);
void glue_visit_type_size(void *v, const char *name, uint64_t *obj);
void glue_visit_type_bool(void *v, const char *name, bool *obj);
void glue_visit_type_str(void *v, const char *name, char **obj);
void glue_visit_type_number(void *v, const char *name, void *obj);
void glue_visit_type_any(void *v, const char *name, void *obj);
void glue_visit_type_null(void *v, const char *name, void *obj);
