void glue_tpm_crb_mmio_read(uint64_t addr, unsigned size, uint32_t val);
void glue_tpm_crb_mmio_write(uint64_t addr, unsigned size, uint32_t val);
void glue_tpm_tis_raise_irq(uint32_t irqmask);
void glue_tpm_tis_new_active_locality(uint8_t locty);
void glue_tpm_tis_abort(uint8_t locty);
void glue_tpm_tis_data_read(uint32_t value, uint32_t off);
void glue_tpm_tis_mmio_read(unsigned size, uint32_t addr, uint32_t val);
void glue_tpm_tis_mmio_write(unsigned size, uint32_t addr, uint32_t val);
void glue_tpm_tis_mmio_write_locty4(void);
void glue_tpm_tis_mmio_write_release_locty(uint8_t locty);
void glue_tpm_tis_mmio_write_locty_req_use(uint8_t locty);
void glue_tpm_tis_mmio_write_next_locty(uint8_t locty);
void glue_tpm_tis_mmio_write_locty_seized(uint8_t locty, uint8_t active);
void glue_tpm_tis_mmio_write_init_abort(void);
void glue_tpm_tis_mmio_write_lowering_irq(void);
void glue_tpm_tis_mmio_write_data2send(uint32_t value, unsigned size);
void glue_tpm_tis_pre_save(uint8_t locty, uint32_t rw_offset);
void glue_tpm_ppi_memset(uint8_t *ptr, size_t size);
void glue_tpm_spapr_do_crq(uint8_t raw1, uint8_t raw2);
void glue_tpm_spapr_do_crq_crq_result(void);
void glue_tpm_spapr_do_crq_crq_complete_result(void);
void glue_tpm_spapr_do_crq_tpm_command(void);
void glue_tpm_spapr_do_crq_tpm_get_rtce_buffer_size(size_t buffersize);
void glue_tpm_spapr_do_crq_get_version(uint32_t version);
void glue_tpm_spapr_do_crq_prepare_to_suspend(void);
void glue_tpm_spapr_do_crq_unknown_msg_type(uint8_t type);
void glue_tpm_spapr_do_crq_unknown_crq(uint8_t raw1, uint8_t raw2);
void glue_tpm_spapr_post_load(void);
void glue_tpm_spapr_caught_response(uint32_t v);
