void glue_xen_default_ioreq_server(void);
void glue_xen_ioreq_server_create(uint32_t id);
void glue_xen_ioreq_server_destroy(uint32_t id);
void glue_xen_ioreq_server_state(uint32_t id, bool enable);
void glue_xen_map_mmio_range(uint32_t id, uint64_t start_addr, uint64_t end_addr);
void glue_xen_unmap_mmio_range(uint32_t id, uint64_t start_addr, uint64_t end_addr);
void glue_xen_map_portio_range(uint32_t id, uint64_t start_addr, uint64_t end_addr);
void glue_xen_unmap_portio_range(uint32_t id, uint64_t start_addr, uint64_t end_addr);
void glue_xen_map_pcidev(uint32_t id, uint8_t bus, uint8_t dev, uint8_t func);
void glue_xen_unmap_pcidev(uint32_t id, uint8_t bus, uint8_t dev, uint8_t func);
void glue_xen_domid_restrict(int err);
void glue_xen_bus_realize(void);
void glue_xen_bus_unrealize(void);
void glue_xen_bus_enumerate(void);
void glue_xen_bus_cleanup(void);
void glue_xen_bus_type_enumerate(const char *type);
void glue_xen_bus_backend_create(const char *type, const char *path);
void glue_xen_bus_device_cleanup(const char *type, char *name);
void glue_xen_bus_add_watch(const char *node, const char *key);
void glue_xen_bus_remove_watch(const char *node, const char *key);
void glue_xen_device_realize(const char *type, char *name);
void glue_xen_device_unrealize(const char *type, char *name);
void glue_xen_device_backend_state(const char *type, char *name, const char *state);
void glue_xen_device_backend_online(const char *type, char *name, bool online);
void glue_xen_device_backend_changed(const char *type, char *name);
void glue_xen_device_frontend_state(const char *type, char *name, const char *state);
void glue_xen_device_frontend_changed(const char *type, char *name);
void glue_xen_device_unplug(const char *type, char *name);
void glue_xen_device_add_watch(const char *type, char *name, const char *node, const char *key);
void glue_xen_device_remove_watch(const char *type, char *name, const char *node, const char *key);
void glue_xs_node_create(const char *node);
void glue_xs_node_destroy(const char *node);
void glue_xs_node_vprintf(char *path, char *value);
void glue_xs_node_vscanf(char *path, char *value);
void glue_xs_node_watch(char *path);
void glue_xs_node_unwatch(char *path);
