void glue_i2c_event(const char *event, uint8_t address);
void glue_i2c_send(uint8_t address, uint8_t data);
void glue_i2c_recv(uint8_t address, uint8_t data);
void glue_aspeed_i2c_bus_cmd(uint32_t cmd, const char *cmd_flags, uint32_t count, uint32_t intr_status);
void glue_aspeed_i2c_bus_raise_interrupt(uint32_t intr_status, const char *str1, const char *str2, const char *str3, const char *str4, const char *str5);
void glue_aspeed_i2c_bus_read(uint32_t busid, uint64_t offset, unsigned size, uint64_t value);
void glue_aspeed_i2c_bus_write(uint32_t busid, uint64_t offset, unsigned size, uint64_t value);
void glue_aspeed_i2c_bus_send(const char *mode, int i, int count, uint8_t byte);
void glue_aspeed_i2c_bus_recv(const char *mode, int i, int count, uint8_t byte);
void glue_npcm7xx_smbus_read(const char *id, uint64_t offset, uint64_t value, unsigned size);
void glue_npcm7xx_smbus_write(const char *id, uint64_t offset, uint64_t value, unsigned size);
void glue_npcm7xx_smbus_start(const char *id, int success);
void glue_npcm7xx_smbus_send_address(const char *id, uint8_t addr, int recv, int success);
void glue_npcm7xx_smbus_send_byte(const char *id, uint8_t value, int success);
void glue_npcm7xx_smbus_recv_byte(const char *id, uint8_t value);
void glue_npcm7xx_smbus_stop(const char *id);
void glue_npcm7xx_smbus_nack(const char *id);
void glue_npcm7xx_smbus_recv_fifo(const char *id, uint8_t received, uint8_t expected);
void glue_pca954x_write_bytes(uint8_t value);
void glue_pca954x_read_data(uint8_t value);
