void glue_v9fs_rcancel(uint16_t tag, uint8_t id);
void glue_v9fs_rerror(uint16_t tag, uint8_t id, int err);
void glue_v9fs_version(uint16_t tag, uint8_t id, int32_t msize, char* version);
void glue_v9fs_version_return(uint16_t tag, uint8_t id, int32_t msize, char* version);
void glue_v9fs_attach(uint16_t tag, uint8_t id, int32_t fid, int32_t afid, char* uname, char* aname);
void glue_v9fs_attach_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path);
void glue_v9fs_stat(uint16_t tag, uint8_t id, int32_t fid);
void glue_v9fs_stat_return(uint16_t tag, uint8_t id, int32_t mode, int32_t atime, int32_t mtime, int64_t length);
void glue_v9fs_getattr(uint16_t tag, uint8_t id, int32_t fid, uint64_t request_mask);
void glue_v9fs_getattr_return(uint16_t tag, uint8_t id, uint64_t result_mask, uint32_t mode, uint32_t uid, uint32_t gid);
void glue_v9fs_walk(uint16_t tag, uint8_t id, int32_t fid, int32_t newfid, uint16_t nwnames);
void glue_v9fs_walk_return(uint16_t tag, uint8_t id, uint16_t nwnames, void* qids);
void glue_v9fs_open(uint16_t tag, uint8_t id, int32_t fid, int32_t mode);
void glue_v9fs_open_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path, int iounit);
void glue_v9fs_lcreate(uint16_t tag, uint8_t id, int32_t dfid, int32_t flags, int32_t mode, uint32_t gid);
void glue_v9fs_lcreate_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path, int32_t iounit);
void glue_v9fs_fsync(uint16_t tag, uint8_t id, int32_t fid, int datasync);
void glue_v9fs_clunk(uint16_t tag, uint8_t id, int32_t fid);
void glue_v9fs_read(uint16_t tag, uint8_t id, int32_t fid, uint64_t off, uint32_t max_count);
void glue_v9fs_read_return(uint16_t tag, uint8_t id, int32_t count, ssize_t err);
void glue_v9fs_readdir(uint16_t tag, uint8_t id, int32_t fid, uint64_t offset, uint32_t max_count);
void glue_v9fs_readdir_return(uint16_t tag, uint8_t id, uint32_t count, ssize_t retval);
void glue_v9fs_write(uint16_t tag, uint8_t id, int32_t fid, uint64_t off, uint32_t count, int cnt);
void glue_v9fs_write_return(uint16_t tag, uint8_t id, int32_t total, ssize_t err);
void glue_v9fs_create(uint16_t tag, uint8_t id, int32_t fid, char* name, int32_t perm, int8_t mode);
void glue_v9fs_create_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path, int iounit);
void glue_v9fs_symlink(uint16_t tag, uint8_t id, int32_t fid,  char* name, char* symname, uint32_t gid);
void glue_v9fs_symlink_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path);
void glue_v9fs_flush(uint16_t tag, uint8_t id, int16_t flush_tag);
void glue_v9fs_link(uint16_t tag, uint8_t id, int32_t dfid, int32_t oldfid, char* name);
void glue_v9fs_remove(uint16_t tag, uint8_t id, int32_t fid);
void glue_v9fs_wstat(uint16_t tag, uint8_t id, int32_t fid, int32_t mode, int32_t atime, int32_t mtime);
void glue_v9fs_mknod(uint16_t tag, uint8_t id, int32_t fid, int mode, int major, int minor);
void glue_v9fs_mknod_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path);
void glue_v9fs_lock(uint16_t tag, uint8_t id, int32_t fid, uint8_t type, uint64_t start, uint64_t length);
void glue_v9fs_lock_return(uint16_t tag, uint8_t id, int8_t status);
void glue_v9fs_getlock(uint16_t tag, uint8_t id, int32_t fid, uint8_t type, uint64_t start, uint64_t length);
void glue_v9fs_getlock_return(uint16_t tag, uint8_t id, uint8_t type, uint64_t start, uint64_t length, uint32_t proc_id);
void glue_v9fs_mkdir(uint16_t tag, uint8_t id, int32_t fid, char* name, int mode, uint32_t gid);
void glue_v9fs_mkdir_return(uint16_t tag, uint8_t id, uint8_t type, uint32_t version, uint64_t path, int err);
void glue_v9fs_xattrwalk(uint16_t tag, uint8_t id, int32_t fid, int32_t newfid, char* name);
void glue_v9fs_xattrwalk_return(uint16_t tag, uint8_t id, int64_t size);
void glue_v9fs_xattrcreate(uint16_t tag, uint8_t id, int32_t fid, char* name, uint64_t size, int flags);
void glue_v9fs_readlink(uint16_t tag, uint8_t id, int32_t fid);
void glue_v9fs_readlink_return(uint16_t tag, uint8_t id, char* target);
void glue_v9fs_setattr(uint16_t tag, uint8_t id, int32_t fid, int32_t valid, int32_t mode, int32_t uid, int32_t gid, int64_t size, int64_t atime_sec, int64_t mtime_sec);
void glue_v9fs_setattr_return(uint16_t tag, uint8_t id);
