void glue_mhp_acpi_invalid_slot_selected(uint32_t slot);
void glue_mhp_acpi_ejecting_invalid_slot(uint32_t slot);
void glue_mhp_acpi_read_addr_lo(uint32_t slot, uint32_t addr);
void glue_mhp_acpi_read_addr_hi(uint32_t slot, uint32_t addr);
void glue_mhp_acpi_read_size_lo(uint32_t slot, uint32_t size);
void glue_mhp_acpi_read_size_hi(uint32_t slot, uint32_t size);
void glue_mhp_acpi_read_pxm(uint32_t slot, uint32_t pxm);
void glue_mhp_acpi_read_flags(uint32_t slot, uint32_t flags);
void glue_mhp_acpi_write_slot(uint32_t slot);
void glue_mhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev);
void glue_mhp_acpi_write_ost_status(uint32_t slot, uint32_t st);
void glue_mhp_acpi_clear_insert_evt(uint32_t slot);
void glue_mhp_acpi_clear_remove_evt(uint32_t slot);
void glue_mhp_acpi_pc_dimm_deleted(uint32_t slot);
void glue_mhp_acpi_pc_dimm_delete_failed(uint32_t slot);
void glue_cpuhp_acpi_invalid_idx_selected(uint32_t idx);
void glue_cpuhp_acpi_read_flags(uint32_t idx, uint8_t flags);
void glue_cpuhp_acpi_write_idx(uint32_t idx);
void glue_cpuhp_acpi_write_cmd(uint32_t idx, uint8_t cmd);
void glue_cpuhp_acpi_read_cmd_data(uint32_t idx, uint32_t data);
void glue_cpuhp_acpi_read_cmd_data2(uint32_t idx, uint32_t data);
void glue_cpuhp_acpi_cpu_has_events(uint32_t idx, bool ins, bool rm);
void glue_cpuhp_acpi_clear_inserting_evt(uint32_t idx);
void glue_cpuhp_acpi_clear_remove_evt(uint32_t idx);
void glue_cpuhp_acpi_ejecting_invalid_cpu(uint32_t idx);
void glue_cpuhp_acpi_ejecting_cpu(uint32_t idx);
void glue_cpuhp_acpi_fw_remove_invalid_cpu(uint32_t idx);
void glue_cpuhp_acpi_fw_remove_cpu(uint32_t idx);
void glue_cpuhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev);
void glue_cpuhp_acpi_write_ost_status(uint32_t slot, uint32_t st);
void glue_acpi_pci_eject_slot(unsigned bsel, unsigned slot);
void glue_acpi_pci_unplug(int bsel, int slot);
void glue_acpi_pci_unplug_request(int bsel, int slot);
void glue_acpi_pci_up_read(uint32_t val);
void glue_acpi_pci_down_read(uint32_t val);
void glue_acpi_pci_features_read(uint32_t val);
void glue_acpi_pci_acpi_index_read(uint32_t val);
void glue_acpi_pci_acpi_index_write(unsigned bsel, unsigned slot, uint32_t aidx);
void glue_acpi_pci_rmv_read(uint32_t val);
void glue_acpi_pci_sel_read(uint32_t val);
void glue_acpi_pci_ej_write(uint64_t addr, uint64_t data);
void glue_acpi_pci_sel_write(uint64_t addr, uint64_t data);
void glue_piix4_gpe_readb(uint64_t addr, unsigned width, uint64_t val);
void glue_piix4_gpe_writeb(uint64_t addr, unsigned width, uint64_t val);
void glue_tco_timer_reload(int ticks, int msec);
void glue_tco_timer_expired(int timeouts_no, bool strap, bool no_reboot);
