void glue_jazzio_read(uint64_t addr, uint32_t ret);
void glue_jazzio_write(uint64_t addr, uint32_t val);
void glue_rc4030_read(uint64_t addr, uint32_t ret);
void glue_rc4030_write(uint64_t addr, uint32_t val);
void glue_ledma_memory_read(uint64_t addr, int len);
void glue_ledma_memory_write(uint64_t addr, int len);
void glue_sparc32_dma_set_irq_raise(void);
void glue_sparc32_dma_set_irq_lower(void);
void glue_espdma_memory_read(uint32_t addr, int len);
void glue_espdma_memory_write(uint32_t addr, int len);
void glue_sparc32_dma_mem_readl(uint64_t addr, uint32_t ret);
void glue_sparc32_dma_mem_writel(uint64_t addr, uint32_t old, uint32_t val);
void glue_sparc32_dma_enable_raise(void);
void glue_sparc32_dma_enable_lower(void);
void glue_i8257_unregistered_dma(int nchan, int dma_pos, int dma_len);
void glue_pl330_fault(void *ptr, uint32_t flags);
void glue_pl330_fault_abort(void);
void glue_pl330_dmaend(void);
void glue_pl330_dmago(void);
void glue_pl330_dmald(uint8_t chan, uint32_t addr, uint32_t size, uint32_t num, char ch);
void glue_pl330_dmakill(void);
void glue_pl330_dmalpend(uint8_t nf, uint8_t bs, uint8_t lc, uint8_t ch, uint8_t flag);
void glue_pl330_dmalpiter(void);
void glue_pl330_dmalpfallthrough(void);
void glue_pl330_dmasev_evirq(uint8_t ev_id);
void glue_pl330_dmasev_event(uint8_t ev_id);
void glue_pl330_dmast(uint8_t chan, uint32_t addr, uint32_t sz, uint32_t num, char ch);
void glue_pl330_dmawfe(uint8_t ev_id);
void glue_pl330_chan_exec_undef(void);
void glue_pl330_exec_cycle(uint32_t addr, uint32_t size);
void glue_pl330_hexdump(uint32_t offset, char *str);
void glue_pl330_exec(void);
void glue_pl330_debug_exec(uint8_t ch);
void glue_pl330_debug_exec_stall(void);
void glue_pl330_iomem_write(uint32_t offset, uint32_t value);
void glue_pl330_iomem_write_clr(int i);
void glue_pl330_iomem_read(uint32_t addr, uint32_t data);
