void glue_bonito_spciconf_small_access(uint64_t addr, unsigned size);
void glue_grackle_set_irq(int irq_num, int level);
void glue_mv64361_region_map(const char *name, uint64_t poffs, uint64_t size, uint64_t moffs);
void glue_mv64361_region_enable(const char *op, int num);
void glue_mv64361_reg_read(uint64_t addr, uint32_t val);
void glue_mv64361_reg_write(uint64_t addr, uint64_t val);
void glue_sabre_set_request(int irq_num);
void glue_sabre_clear_request(int irq_num);
void glue_sabre_config_write(uint64_t addr, uint64_t val);
void glue_sabre_config_read(uint64_t addr, uint64_t val);
void glue_sabre_pci_config_write(uint64_t addr, uint64_t val);
void glue_sabre_pci_config_read(uint64_t addr, uint64_t val);
void glue_sabre_pci_set_irq(int irq_num, int level);
void glue_sabre_pci_set_obio_irq(int irq_num, int level);
void glue_unin_set_irq(int irq_num, int level);
void glue_unin_get_config_reg(uint32_t reg, uint32_t addr, uint32_t retval);
void glue_unin_data_write(uint64_t addr, unsigned len, uint64_t val);
void glue_unin_data_read(uint64_t addr, unsigned len, uint64_t val);
void glue_unin_write(uint64_t addr, uint64_t value);
void glue_unin_read(uint64_t addr, uint64_t value);
void glue_pnv_phb4_xive_notify(uint64_t notif_port, uint64_t data);
