void glue_parallel_ioport_read(const char *desc, uint16_t addr, uint8_t value);
void glue_parallel_ioport_write(const char *desc, uint16_t addr, uint8_t value);
void glue_serial_read(uint16_t addr, uint8_t value);
void glue_serial_write(uint16_t addr, uint8_t value);
void glue_serial_update_parameters(uint64_t baudrate, char parity, int data_bits, int stop_bits);
void glue_virtio_serial_send_control_event(unsigned int port, uint16_t event, uint16_t value);
void glue_virtio_serial_throttle_port(unsigned int port, bool throttle);
void glue_virtio_serial_handle_control_message(uint16_t event, uint16_t value);
void glue_virtio_serial_handle_control_message_port(unsigned int port);
void glue_virtio_console_flush_buf(unsigned int port, size_t len, ssize_t ret);
void glue_virtio_console_chr_read(unsigned int port, int size);
void glue_virtio_console_chr_event(unsigned int port, int event);
void glue_goldfish_tty_read(void *dev, unsigned int addr, unsigned int size, uint64_t value);
void glue_goldfish_tty_write(void *dev, unsigned int addr, unsigned int size, uint64_t value);
void glue_goldfish_tty_can_receive(void *dev, unsigned int available);
void glue_goldfish_tty_receive(void *dev, unsigned int size);
void glue_goldfish_tty_reset(void *dev);
void glue_goldfish_tty_realize(void *dev);
void glue_goldfish_tty_unrealize(void *dev);
void glue_goldfish_tty_instance_init(void *dev);
void glue_grlib_apbuart_event(int event);
void glue_grlib_apbuart_writel_unknown(uint64_t addr, uint32_t value);
void glue_grlib_apbuart_readl_unknown(uint64_t addr);
void glue_escc_hard_reset(void);
void glue_escc_soft_reset_chn(char channel);
void glue_escc_put_queue(char channel, int b);
void glue_escc_get_queue(char channel, int val);
void glue_escc_update_irq(int irq);
void glue_escc_update_parameters(char channel, int speed, int parity, int data_bits, int stop_bits);
void glue_escc_mem_writeb_ctrl(char channel, uint32_t reg, uint32_t val);
void glue_escc_mem_writeb_data(char channel, uint32_t val);
void glue_escc_mem_readb_ctrl(char channel, uint32_t reg, uint8_t val);
void glue_escc_mem_readb_data(char channel, uint32_t ret);
void glue_escc_serial_receive_byte(char channel, int ch);
void glue_escc_sunkbd_event_in(int ch, const char *name, int down);
void glue_escc_sunkbd_event_out(int ch);
void glue_escc_kbd_command(int val);
void glue_escc_sunmouse_event(int dx, int dy, int buttons_state);
void glue_pl011_irq_state(int level);
void glue_pl011_read(uint32_t addr, uint32_t value);
void glue_pl011_read_fifo(int read_count);
void glue_pl011_write(uint32_t addr, uint32_t value);
void glue_pl011_can_receive(uint32_t lcr, int read_count, int r);
void glue_pl011_put_fifo(uint32_t c, int read_count);
void glue_pl011_put_fifo_full(void);
void glue_pl011_baudrate_change(unsigned int baudrate, uint64_t clock, uint32_t ibrd, uint32_t fbrd);
void glue_cmsdk_apb_uart_read(uint64_t offset, uint64_t data, unsigned size);
void glue_cmsdk_apb_uart_write(uint64_t offset, uint64_t data, unsigned size);
void glue_cmsdk_apb_uart_reset(void);
void glue_cmsdk_apb_uart_receive(uint8_t c);
void glue_cmsdk_apb_uart_tx_pending(void);
void glue_cmsdk_apb_uart_tx(uint8_t c);
void glue_cmsdk_apb_uart_set_params(int speed);
void glue_nrf51_uart_read(uint64_t addr, uint64_t r, unsigned int size);
void glue_nrf51_uart_write(uint64_t addr, uint64_t value, unsigned int size);
void glue_shakti_uart_read(uint64_t addr, uint16_t r, unsigned int size);
void glue_shakti_uart_write(uint64_t addr, uint64_t value, unsigned int size);
void glue_exynos_uart_dmabusy(uint32_t channel);
void glue_exynos_uart_dmaready(uint32_t channel);
void glue_exynos_uart_irq_raised(uint32_t channel, uint32_t reg);
void glue_exynos_uart_irq_lowered(uint32_t channel);
void glue_exynos_uart_update_params(uint32_t channel, int speed, uint8_t parity, int data, int stop, uint64_t wordtime);
void glue_exynos_uart_write(uint32_t channel, uint32_t offset, const char *name, uint64_t val);
void glue_exynos_uart_read(uint32_t channel, uint32_t offset, const char *name, uint64_t val);
void glue_exynos_uart_rx_fifo_reset(uint32_t channel);
void glue_exynos_uart_tx_fifo_reset(uint32_t channel);
void glue_exynos_uart_tx(uint32_t channel, uint8_t ch);
void glue_exynos_uart_intclr(uint32_t channel, uint32_t reg);
void glue_exynos_uart_ro_write(uint32_t channel, const char *name, uint32_t reg);
void glue_exynos_uart_rx(uint32_t channel, uint8_t ch);
void glue_exynos_uart_rx_error(uint32_t channel);
void glue_exynos_uart_wo_read(uint32_t channel, const char *name, uint32_t reg);
void glue_exynos_uart_rxsize(uint32_t channel, uint32_t size);
void glue_exynos_uart_channel_error(uint32_t channel);
void glue_exynos_uart_rx_timeout(uint32_t channel, uint32_t stat, uint32_t intsp);
void glue_cadence_uart_baudrate(unsigned baudrate);
void glue_sh_serial_read(char *id, unsigned size, uint64_t offs, uint64_t val);
void glue_sh_serial_write(char *id, unsigned size, uint64_t offs, uint64_t val);
