void glue_tpm_passthrough_handle_request(void *cmd);
void glue_tpm_passthrough_reset(void);
void glue_tpm_util_get_buffer_size_hdr_len(uint32_t len, size_t expected);
void glue_tpm_util_get_buffer_size_len(uint32_t len, size_t expected);
void glue_tpm_util_get_buffer_size_hdr_len2(uint32_t len, size_t expected);
void glue_tpm_util_get_buffer_size_len2(uint32_t len, size_t expected);
void glue_tpm_util_get_buffer_size(size_t len);
void glue_tpm_util_show_buffer(const char *direction, size_t len, const char *buf);
void glue_tpm_emulator_set_locality(uint8_t locty);
void glue_tpm_emulator_handle_request(void);
void glue_tpm_emulator_probe_caps(uint64_t caps);
void glue_tpm_emulator_set_buffer_size(uint32_t buffersize, uint32_t minsize, uint32_t maxsize);
void glue_tpm_emulator_startup_tpm_resume(bool is_resume, size_t buffersize);
void glue_tpm_emulator_get_tpm_established_flag(uint8_t flag);
void glue_tpm_emulator_cancel_cmd_not_supt(void);
void glue_tpm_emulator_handle_device_opts_tpm12(void);
void glue_tpm_emulator_handle_device_opts_tpm2(void);
void glue_tpm_emulator_handle_device_opts_unspec(void);
void glue_tpm_emulator_handle_device_opts_startup_error(void);
void glue_tpm_emulator_get_state_blob(uint8_t type, uint32_t size, uint32_t flags);
void glue_tpm_emulator_set_state_blob(uint8_t type, uint32_t size, uint32_t flags);
void glue_tpm_emulator_set_state_blobs(void);
void glue_tpm_emulator_set_state_blobs_error(const char *msg);
void glue_tpm_emulator_set_state_blobs_done(void);
void glue_tpm_emulator_pre_save(void);
void glue_tpm_emulator_inst_init(void);
