void glue_rdma_check_dev_attr(const char *name, int max_bk, int max_fe);
void glue_rdma_create_ah_cache_hit(uint64_t subnet, uint64_t if_id);
void glue_rdma_create_ah_cache_miss(uint64_t subnet, uint64_t if_id);
void glue_rdma_poll_cq(int ne, void *ibcq);
void glue_rdmacm_mux(const char *title, int msg_type, int op_code);
void glue_rdmacm_mux_check_op_status(int msg_type, int op_code, int err_code);
void glue_rdma_mad_message(const char *title, int len, char *data);
void glue_rdma_backend_rc_qp_state_init(uint32_t qpn);
void glue_rdma_backend_ud_qp_state_init(uint32_t qpn, uint32_t qkey);
void glue_rdma_backend_rc_qp_state_rtr(uint32_t qpn, uint64_t subnet, uint64_t ifid, uint8_t sgid_idx, uint32_t dqpn, uint32_t rq_psn);
void glue_rdma_backend_ud_qp_state_rtr(uint32_t qpn, uint32_t qkey);
void glue_rdma_backend_rc_qp_state_rts(uint32_t qpn, uint32_t sq_psn);
void glue_rdma_backend_ud_qp_state_rts(uint32_t qpn, uint32_t sq_psn, uint32_t qkey);
void glue_rdma_backend_get_gid_index(uint64_t subnet, uint64_t ifid, int gid_idx);
void glue_rdma_backend_gid_change(const char *op, uint64_t subnet, uint64_t ifid);
void glue_rdma_res_tbl_get(char *name, uint32_t handle);
void glue_rdma_res_tbl_alloc(char *name, uint32_t handle);
void glue_rdma_res_tbl_dealloc(char *name, uint32_t handle);
void glue_rdma_rm_alloc_mr(uint32_t mr_handle, void *host_virt, uint64_t guest_start, uint64_t guest_length, int access_flags);
void glue_rdma_rm_dealloc_mr(uint32_t mr_handle, uint64_t guest_start);
void glue_rdma_rm_alloc_qp(uint32_t rm_qpn, uint32_t backend_qpn, uint8_t qp_type);
void glue_rdma_rm_modify_qp(uint32_t qpn, uint32_t attr_mask, int qp_state, uint8_t sgid_idx);
void glue_rdma_pci_dma_map(uint64_t addr, void *vaddr, uint64_t len);
void glue_rdma_pci_dma_unmap(void *vaddr);
