void glue_loader_write_rom(const char *name, uint64_t gpa, uint64_t size, bool isrom);
void glue_qdev_reset(void *obj, const char *objtype);
void glue_qdev_reset_all(void *obj, const char *objtype);
void glue_qdev_reset_tree(void *obj, const char *objtype);
void glue_qbus_reset(void *obj, const char *objtype);
void glue_qbus_reset_all(void *obj, const char *objtype);
void glue_qbus_reset_tree(void *obj, const char *objtype);
void glue_qdev_update_parent_bus(void *obj, const char *objtype, void *oldp, const char *oldptype, void *newp, const char *newptype);
void glue_resettable_reset(void *obj, int cold);
void glue_resettable_reset_assert_begin(void *obj, int cold);
void glue_resettable_reset_assert_end(void *obj);
void glue_resettable_reset_release_begin(void *obj, int cold);
void glue_resettable_reset_release_end(void *obj);
void glue_resettable_change_parent(void *obj, void *o, unsigned oc, void *n, unsigned nc);
void glue_resettable_phase_enter_begin(void *obj, const char *objtype, unsigned count, int type);
void glue_resettable_phase_enter_exec(void *obj, const char *objtype, int type, int has_method);
void glue_resettable_phase_enter_end(void *obj, const char *objtype, unsigned count);
void glue_resettable_phase_hold_begin(void *obj, const char *objtype, unsigned count, int type);
void glue_resettable_phase_hold_exec(void *obj, const char *objtype, int has_method);
void glue_resettable_phase_hold_end(void *obj, const char *objtype, unsigned count);
void glue_resettable_phase_exit_begin(void *obj, const char *objtype, unsigned count, int type);
void glue_resettable_phase_exit_exec(void *obj, const char *objtype, int has_method);
void glue_resettable_phase_exit_end(void *obj, const char *objtype, unsigned count);
void glue_resettable_transitional_function(void *obj, const char *objtype);
void glue_clock_set_source(const char *clk, const char *src);
void glue_clock_disconnect(const char *clk);
void glue_clock_set(const char *clk, uint64_t old, uint64_t new);
void glue_clock_propagate(const char *clk);
void glue_clock_update(const char *clk, const char *src, uint64_t hz, int cb);
void glue_clock_set_mul_div(const char *clk, uint32_t oldmul, uint32_t mul, uint32_t olddiv, uint32_t div);
