void glue_qio_task_new(void *task, void *source, void *func, void *opaque);
void glue_qio_task_complete(void *task);
void glue_qio_task_thread_start(void *task, void *worker, void *opaque);
void glue_qio_task_thread_run(void *task);
void glue_qio_task_thread_exit(void *task);
void glue_qio_task_thread_result(void *task);
void glue_qio_task_thread_source_attach(void *task, void *source);
void glue_qio_task_thread_source_cancel(void *task, void *source);
void glue_qio_channel_socket_new(void *ioc);
void glue_qio_channel_socket_new_fd(void *ioc, int fd);
void glue_qio_channel_socket_connect_sync(void *ioc, void *addr);
void glue_qio_channel_socket_connect_async(void *ioc, void *addr);
void glue_qio_channel_socket_connect_fail(void *ioc);
void glue_qio_channel_socket_connect_complete(void *ioc, int fd);
void glue_qio_channel_socket_listen_sync(void *ioc, void *addr, int num);
void glue_qio_channel_socket_listen_async(void *ioc, void *addr, int num);
void glue_qio_channel_socket_listen_fail(void *ioc);
void glue_qio_channel_socket_listen_complete(void *ioc, int fd);
void glue_qio_channel_socket_dgram_sync(void *ioc, void *localAddr, void *remoteAddr);
void glue_qio_channel_socket_dgram_async(void *ioc, void *localAddr, void *remoteAddr);
void glue_qio_channel_socket_dgram_fail(void *ioc);
void glue_qio_channel_socket_dgram_complete(void *ioc, int fd);
void glue_qio_channel_socket_accept(void *ioc);
void glue_qio_channel_socket_accept_fail(void *ioc);
void glue_qio_channel_socket_accept_complete(void *ioc, void *cioc, int fd);
void glue_qio_channel_file_new_fd(void *ioc, int fd);
void glue_qio_channel_file_new_path(void *ioc, const char *path, int flags, int mode, int fd);
void glue_qio_channel_tls_new_client(void *ioc, void *master, void *creds, const char *hostname);
void glue_qio_channel_tls_new_server(void *ioc, void *master, void *creds, const char *aclname);
void glue_qio_channel_tls_handshake_start(void *ioc);
void glue_qio_channel_tls_handshake_pending(void *ioc, int status);
void glue_qio_channel_tls_handshake_fail(void *ioc);
void glue_qio_channel_tls_handshake_complete(void *ioc);
void glue_qio_channel_tls_credentials_allow(void *ioc);
void glue_qio_channel_tls_credentials_deny(void *ioc);
void glue_qio_channel_websock_new_server(void *ioc, void *master);
void glue_qio_channel_websock_handshake_start(void *ioc);
void glue_qio_channel_websock_handshake_pending(void *ioc, int status);
void glue_qio_channel_websock_handshake_reply(void *ioc);
void glue_qio_channel_websock_handshake_fail(void *ioc, const char *msg);
void glue_qio_channel_websock_handshake_complete(void *ioc);
void glue_qio_channel_websock_http_greeting(void *ioc, const char *greeting);
void glue_qio_channel_websock_http_request(void *ioc, const char *protocols, const char *version, const char *host, const char *connection, const char *upgrade, const char *key);
void glue_qio_channel_websock_header_partial_decode(void *ioc, size_t payloadlen, unsigned char fin, unsigned char opcode, unsigned char has_mask);
void glue_qio_channel_websock_header_full_decode(void *ioc, size_t headerlen, size_t payloadlen, uint32_t mask);
void glue_qio_channel_websock_payload_decode(void *ioc, uint8_t opcode, size_t payload_remain);
void glue_qio_channel_websock_encode(void *ioc, uint8_t opcode, size_t payloadlen, size_t headerlen);
void glue_qio_channel_websock_close(void *ioc);
void glue_qio_channel_command_new_pid(void *ioc, int writefd, int readfd, int pid);
void glue_qio_channel_command_new_spawn(void *ioc, const char *binary, int flags);
void glue_qio_channel_command_abort(void *ioc, int pid);
void glue_qio_channel_command_wait(void *ioc, int pid, int ret, int status);
