void glue_allwinner_sdhost_set_inserted(bool inserted);
void glue_allwinner_sdhost_process_desc(uint64_t desc_addr, uint32_t desc_size, bool is_write, uint32_t max_bytes);
void glue_allwinner_sdhost_read(uint64_t offset, uint64_t data, unsigned size);
void glue_allwinner_sdhost_write(uint64_t offset, uint64_t data, unsigned size);
void glue_allwinner_sdhost_update_irq(uint32_t irq);
void glue_bcm2835_sdhost_read(uint64_t offset, uint64_t data, unsigned size);
void glue_bcm2835_sdhost_write(uint64_t offset, uint64_t data, unsigned size);
void glue_bcm2835_sdhost_edm_change(const char *why, uint32_t edm);
void glue_bcm2835_sdhost_update_irq(uint32_t irq);
void glue_sdbus_command(const char *bus_name, uint8_t cmd, uint32_t arg);
void glue_sdbus_read(const char *bus_name, uint8_t value);
void glue_sdbus_write(const char *bus_name, uint8_t value);
void glue_sdbus_set_voltage(const char *bus_name, uint16_t millivolts);
void glue_sdbus_get_dat_lines(const char *bus_name, uint8_t dat_lines);
void glue_sdbus_get_cmd_line(const char *bus_name, bool cmd_line);
void glue_sdhci_set_inserted(const char *level);
void glue_sdhci_send_command(uint8_t cmd, uint32_t arg);
void glue_sdhci_error(const char *msg);
void glue_sdhci_response4(uint32_t r0);
void glue_sdhci_response16(uint32_t r3, uint32_t r2, uint32_t r1, uint32_t r0);
void glue_sdhci_end_transfer(uint8_t cmd, uint32_t arg);
void glue_sdhci_adma(const char *desc, uint32_t sysad);
void glue_sdhci_adma_loop(uint64_t addr, uint16_t length, uint8_t attr);
void glue_sdhci_adma_transfer_completed(void);
void glue_sdhci_access(const char *access, unsigned int size, uint64_t offset, const char *dir, uint64_t val, uint64_t val2);
void glue_sdhci_read_dataport(uint16_t data_count);
void glue_sdhci_write_dataport(uint16_t data_count);
void glue_sdhci_capareg(const char *desc, uint16_t val);
void glue_sdcard_normal_command(const char *proto, const char *cmd_desc, uint8_t cmd, uint32_t arg, const char *state);
void glue_sdcard_app_command(const char *proto, const char *acmd_desc, uint8_t acmd, uint32_t arg, const char *state);
void glue_sdcard_response(const char *rspdesc, int rsplen);
void glue_sdcard_powerup(void);
void glue_sdcard_inquiry_cmd41(void);
void glue_sdcard_reset(void);
void glue_sdcard_set_blocklen(uint16_t length);
void glue_sdcard_inserted(bool readonly);
void glue_sdcard_ejected(void);
void glue_sdcard_erase(uint32_t first, uint32_t last);
void glue_sdcard_lock(void);
void glue_sdcard_unlock(void);
void glue_sdcard_read_block(uint64_t addr, uint32_t len);
void glue_sdcard_write_block(uint64_t addr, uint32_t len);
void glue_sdcard_write_data(const char *proto, const char *cmd_desc, uint8_t cmd, uint8_t value);
void glue_sdcard_read_data(const char *proto, const char *cmd_desc, uint8_t cmd, uint32_t length);
void glue_sdcard_set_voltage(uint16_t millivolts);
void glue_pxa2xx_mmci_read(uint8_t size, uint32_t addr, uint32_t value);
void glue_pxa2xx_mmci_write(uint8_t size, uint32_t addr, uint32_t value);
void glue_pl181_command_send(uint8_t cmd, uint32_t arg);
void glue_pl181_command_sent(void);
void glue_pl181_command_response_pending(void);
void glue_pl181_command_timeout(void);
void glue_pl181_fifo_push(uint32_t data);
void glue_pl181_fifo_pop(uint32_t data);
void glue_pl181_fifo_transfer_complete(void);
void glue_pl181_data_engine_idle(void);
void glue_aspeed_sdhci_read(uint64_t addr, uint32_t size, uint64_t data);
void glue_aspeed_sdhci_write(uint64_t addr, uint32_t size, uint64_t data);
